language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t alex8ya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alex8ya/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-472911463497"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  
